// <auto-generated />
using System;
using ClubeApi.Infraestruture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubeApi.Migrations
{
    [DbContext(typeof(ClubeDbContext))]
    [Migration("20220107234428_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClubeApi.Domain.Socio", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idSocio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("nome");

                    b.Property<int>("NumeroCartao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numeroCartao");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("parentesco");

                    b.HasKey("Id");

                    b.ToTable("socio", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
